os: linux
arch: arm64-graviton2
dist: trusty

sudo: required
language: java
# use Java 8

services:
  - docker

branches:
  only:
    - master
    - develop
    - main

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sudo sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
  - make fmt && git diff --exit-code
  - make test

script:
  - 'if [[ "$TRAVIS_BRANCH" == "main" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then make push IMAGE_VERSION=latest; fi'

deploy:
  provider: script
  script:
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master