os: linux
arch: arm64-graviton2
dist: trusty

sudo: required
language: java
# use Java 8

services:
  - docker

branches:
  only:
    - master
    - develop
    - main

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sudo sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

